### ISSUE TITLE
Need advice

### ISSUE THREAD

**Issue by blefony** [boorzz/samp-opws-fix#2]
Hi!  I don't know much about lagcomp yet.  Should I keep it on?  Or is it better to turn off and use your fix?  What is better for RP server? Thank you.

**Comment by boorzz** [comment]
Hi.

To be honest I wouldn't know how to answer which is better, since it depends on what type of community you would like to have on your server, the communities of lagshot (lagcomp off) and skinshot (lagcomp on) are usually separated and so different.

But if I had to choose one I would tell you skinshot, since an extra fix wouldn't be needed and people would already know where to shoot. On lagshot the people would need to know how to calcule the lag point to know where to shoot, also I don't know what is preferred in RP because I don't play it too much, but I think the most common is to use skinshot due to realism.

**Comment by blefony** [comment]
Okay, then I'll experiment with this and that. Thank you so much! :)
